s=set()
num = int(input("enter the number:- "))
s.add(num)
num = int(input("enter the number:- "))
s.add(num)
num = int(input("enter the number:- "))
s.add(num)
num = int(input("enter the number:- "))
s.add(num)
num = int(input("enter the number:- "))
s.add(num)
num = int(input("enter the number:- "))
s.add(num)
num = int(input("enter the number:- "))
s.add(num)
num = int(input("enter the number:- "))
s.add(num)

print(s)